approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

supportedArchitectures:
  os:
    - current
    - linux
  libc:
    - current
    - glibc
    - musl
