services:
  gateway:
    image: ${REGISTRY}/safety-docs-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-node
      - api

  frontend-node:
    image: ${REGISTRY}/safety-docs-frontend-node:${IMAGE_TAG}
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://api.safety-docs.ru
      - INTERNAL_BACKEND_URL=http://api
      - PORT=3000
    expose:
      - "3000"
    depends_on:
      - api

  api:
    image: ${REGISTRY}/safety-docs-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm
      - api-php-cli
    volumes:
      - /home/deploy/storage/templates:/app/public/templates

  api-php-fpm:
    image: ${REGISTRY}/safety-docs-api-php-fpm:${IMAGE_TAG}
    restart: always
    volumes:
      - /home/deploy/storage/templates:/app/public/templates
    environment:
      APP_DEBUG: 0
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      APP_ENV: prod
      DB_HOST: mysql
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_HOST: ${API_MAILER_HOST}
      MAILER_PORT: ${API_MAILER_PORT}
      MAILER_USER: ${API_MAILER_USER}
      MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: ${API_MAILER_FROM_NAME}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      YOOKASSA_RETURN_URL: ${YOOKASSA_RETURN_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      AUTH_LOGIN: ${AUTH_LOGIN}
      AUTH_PASSWORD: ${AUTH_PASSWORD}


  api-php-cli:
    image: ${REGISTRY}/safety-docs-api-php-cli:${IMAGE_TAG}
    environment:
      APP_DEBUG: 0
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      APP_ENV: prod
      DB_HOST: mysql
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_HOST: ${API_MAILER_HOST}
      MAILER_PORT: ${API_MAILER_PORT}
      MAILER_USER: ${API_MAILER_USER}
      MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: ${API_MAILER_FROM_NAME}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      YOOKASSA_RETURN_URL: ${YOOKASSA_RETURN_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      AUTH_LOGIN: ${AUTH_LOGIN}
      AUTH_PASSWORD: ${AUTH_LOGIN}


  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: app
      MYSQL_PASSWORD: ${API_DB_PASSWORD}
      MYSQL_DATABASE: app
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33061:3306"

volumes:
  mysql:



