name: ci.yml
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - name: Cache API Composer dependencies
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache Node Modules (NPM)
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Dev Init
        run: make init
